skip_tags: true

environment:
  PYTHON: C:\\Python36-x64

  CONAN_PRINT_RUN_COMMANDS: 1
  CONAN_LOG_RUN_TO_OUTPUT: 1

  CONAN_USERNAME: odant
  CONAN_REFERENCE: get_vcvars/1.0

  CONAN_UPLOAD: https://api.bintray.com/conan/odant/conan
  CONAN_LOGIN_USERNAME: dvetutnev
  CONAN_STABLE_BRANCH_PATTERN: release/*

  CONAN_VISUAL_RUNTIMES: MD

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_ARCHS: x86_64

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_ARCHS: x86

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_ARCHS: x86_64

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_ARCHS: x86

install:
  - git submodule update --init --recursive

  - set PATH=%PYTHON%;%PYTHON%\\Scripts\\;%PATH%
  - pip install conan
  - pip install conan_package_tools
  - pip install nose2

  - conan user

build: false

test_script:
  - python --version
  - nose2
  - python build.py

